name: Sync to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Push to GitHub Pages repo
        uses: ad-m/github-push-action@v0.8.0
        with:
          repository: hritikkushwaha/hritikkushwaha.github.io
          github_token: ${{ secrets.REPO_SYNC_TOKEN }}  # Must have repo permissions
          branch: main  # GitHub Pages typically uses `main` or `gh-pages`
          force: true  # Overwrites target repo (use `false` for merge)
